/* AGENTS.md and README template generation for spec-coding. */
import { businessConfirmationBullets, currentTaskInstructionBullets, engineeringRuleSections } from "./markdown.js";

export function agentsMd(projectName: string): string {
  return [
    "# AGENTS.md",
    "",
    `Project: ${projectName}`,
    "",
    "## Operating Rules",
    "",
    "1. Before any code or documentation change, call `spec_context` and read its output first.",
    "2. Treat specs and open TODOs as the source of truth.",
    "3. Make small, focused, reversible changes.",
    "4. Follow the engineering and business confirmation rules below.",
    "5. Preserve compatibility unless the spec says otherwise.",
    "6. Prefer mature libraries over hand-rolled implementations.",
    "7. Ask before unclear, risky, or high-impact decisions.",
    "8. Update TODOs, checkpoints, and verification results after each completed item.",
    "9. Keep code organized by business meaning and clear boundaries.",
    "10. Avoid unrelated reshuffles, clever code, and abstraction without benefit.",
    "",
    "## Engineering Principles",
    "",
    "These rules are mandatory, not suggestions.",
    "",
    ...engineeringRuleSections(),
    "",
    "## Business Confirmation Rules",
    "",
    "These rules are mandatory, not suggestions.",
    "",
    ...businessConfirmationBullets(),
    "",
    "## Current Task Protocol",
    "",
    ...currentTaskInstructionBullets(),
    "",
    "## Project Notes",
    "",
    "- Configuration should be centralized.",
    "- Example code and production code should stay separate.",
    "- Readme and decision notes should stay up to date.",
    "- Tests live in `test/` and core logic should remain easy to unit test."
  ].join("\n");
}

export function specsReadme(projectName: string): string {
  return [
    `# ${projectName} Specs`,
    "",
    "本目录用于 spec coding：先写清楚规格，再让 AI 按规格修改代码和测试。",
    "",
    "## 前置要求",
    "",
    "任何代码或文档变更之前，必须先调用 `spec_context` 并读取输出。",
    "如果当前没有 `spec_context` 结果，就不要直接开始实现。",
    "",
    "## 工作流",
    "",
    "1. 先调用 `spec_context`，确认当前任务的 spec、TODO 和工程约束。",
    "2. 没有 spec 的旧系统，先用 MCP 从源码反推 `review/` specs。",
    "3. 用户审查 `review/*.md`，把源码事实改成真实业务规格。",
    "4. 要开发时，把 spec 放到 `active/`，或直接让 MCP 读取指定 spec。",
    "5. Codex 按 spec 修改代码和测试。",
    "6. 验证通过后，把 spec 移到 `done/`。",
    "",
    "## 状态",
    "",
    "- `source-derived/current-code`：从现有源码反推，表示当前代码大概率已有对应实现，待用户审查。",
    "- `draft`：用户正在描述需求，尚未实现。",
    "- `active`：准备实现或正在实现。",
    "- `todo`：轻量任务清单，AI 应按未勾选项顺序执行。",
    "- `done`：代码和测试已按该 spec 完成。",
    "",
    "## 目录",
    "",
    "- `review/`：从源码反推的待审查 specs。",
    "- `active/`：当前要实现的 specs。",
    "- `todo/`：可执行 TODO 清单，适合拆分小任务或补充实现步骤。",
    "- `done/`：已经完成的 specs。",
    "- `templates/`：新建 feature、bugfix、removal spec 的模板。"
  ].join("\n");
}
